name: ag_ui_demo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  ag_ui:
    path: /Users/punk1290/git/ag-ui/sdks/community/dart
  http: ^1.2.0
  file_picker: ^8.1.7

dev_dependencies:
  flutter_lints: ^6.0.0

dependency_overrides:
  meta: ^1.17.0

flutter:
  uses-material-design: true
